[tool.poetry]
name = "nfmer"
version = "0.1.0"
description = ""
authors = ["Piotr Dindorf <piotr.dindorf@mailo.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.28.2"
bs4 = "^0.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
